import { EParticleShadingMode } from "./particles";

export const FlameParticlesDesc = {
    inName: "Flame Particles",
    inNumSpawners2D: 64,
    inNumParticlesPerSpawner: 1,
    inSpawnRange: { x: 2.99, y: 1000.0 }, //TODO:depends on temperature
    inParticleLife: 2.4,
    inNumLoops: 3.0,
    inTextureFileName: "assets/sprites/Flame02_16x4.png",
    inFlipbookSizeRC: { x: 16.0, y: 4.0 },
    inDefaultSize: { x: 0.2 * 1.0, y: 0.5 * 1.0 },
    inSizeRangeMinMax: { x: 0.45, y: 1.2 },
    inSizeClampMax: { x: 0.35, y: 0.0 },
    inInitialVelocityScale: 0.0,
    inVelocityFieldForceScale: 0.0,
    inBuoyancyForceScale: 0.0,
    inbOriginAtCenter: false,
    inEAlphaFade: 1,
    inESpecificShadingMode: EParticleShadingMode.Flame,
};

export const EmberParticlesDesc = {
    inName: "Ember Particles",
    inNumSpawners2D: 64,
    inNumParticlesPerSpawner: 1,
    inSpawnRange: { x: 0.9, y: 1000.0 },
    inParticleLife: 2.8,
    inNumLoops: 1.0,
    inTextureFileName: "",
    inFlipbookSizeRC: { x: 16.0, y: 4.0 },
    inDefaultSize: { x: 0.125 * 0.2, y: 0.125 * 0.2 },
    inSizeRangeMinMax: { x: 0.25, y: 1.25 },
    inSizeClampMax: { x: 0.0, y: 0.0 },
    inInitialVelocityScale: 35.0,
    inVelocityFieldForceScale: 100.0,
    inBuoyancyForceScale: 5.0,
    inDownwardForceScale: 1.0,
    inbOriginAtCenter: true,
    inbMotionBasedTransform: true,
    inESpecificShadingMode: EParticleShadingMode.Embers,
};

export const SmokeParticlesDesc = {
    inName: "Smoke Particles",
    inNumSpawners2D: 32,
    inNumParticlesPerSpawner: 2,
    inSpawnRange: { x: 0.9, y: 1000.0 },
    inParticleLife: 3.5,
    inNumLoops: 1.0,
    inTextureFileName: "assets/sprites/Explosion01-nofire_5x5.png",
    inFlipbookSizeRC: { x: 5.0, y: 5.0 },
    inDefaultSize: { x: 2.0 * 0.225, y: 2.125 * 0.225 },
    inSizeRangeMinMax: { x: 0.7, y: 1.0 },
    inSizeClampMax: { x: 0.7, y: 0.7 },
    inInitialVelocityScale: 5.0,
    inVelocityFieldForceScale: 10.0,
    inBuoyancyForceScale: 10,
    inDownwardForceScale: 0.25,
    inAlphaScale: 0.25,
    inEAlphaFade: 2,
    inbOriginAtCenter: true,
    inESpecificShadingMode: EParticleShadingMode.Smoke,
};

export const AfterBurnSmokeParticlesDesc = {
    inName: "After Burn Smoke Particles",
    inNumSpawners2D: 8,
    inNumParticlesPerSpawner: 1,
    inSpawnRange: { x: 0.001, y: 0.1 },
    inParticleLife: 12.7,
    inNumLoops: 4.0,
    inTextureFileName: "assets/sprites/DiscSmoke01_16x4.png",
    inFlipbookSizeRC: { x: 16.0, y: 4.0 },
    inDefaultSize: { x: 2.0 * 0.2, y: 4.125 * 0.2 },
    inSizeRangeMinMax: { x: 0.99, y: 1.01 },
    inSizeClampMax: { x: 1.0, y: 1.0 },
    inInitialVelocityScale: 0.01,
    inVelocityFieldForceScale: 0.0,
    inBuoyancyForceScale: 0,
    inDownwardForceScale: 0.0,
    inbOriginAtCenter: false,
    inEAlphaFade: 1,
    inAlphaScale: 1.0,
    inBrightness: 0.0,
    inESpecificShadingMode: EParticleShadingMode.Smoke,
};

export const AfterBurnAshesParticlesDesc = {
    inName: "Ashes Particles",
    inNumSpawners2D: 16,
    inNumParticlesPerSpawner: 1,
    inSpawnRange: { x: 0.001, y: 1.0 },
    inParticleLife: 6.8,
    inNumLoops: 1.0,
    //inTextureFileName: "",
    inTextureFileName: "assets/perlinNoise512.png",
    inFlipbookSizeRC: { x: 5.0, y: 5.0 },
    inDefaultSize: { x: 0.075, y: 0.075 },
    inSizeRangeMinMax: { x: 0.45, y: 1.0 },
    inSizeClampMax: { x: 0.0, y: 0.0 },
    inInitialVelocityScale: 10.0,
    inVelocityFieldForceScale: 50.0,
    inBuoyancyForceScale: 5.0,
    inDownwardForceScale: 0.1,
    inbOriginAtCenter: true,
    inESpecificShadingMode: EParticleShadingMode.Ashes,
};
